ExpensesProjectMaster/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExpensesProjectMaster.Models.Entities;
using ExpensesProjectMaster.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ExpensesProjectMaster.Controllers
{
    [Authorize]
    public class ExpensesController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        // GET: Expenses
        public ActionResult Index()
        {
            var employee = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault();
            if (employee != null)
            {
                ViewBag.AlertMessage = TempData["AlertMsg"] as string;
                var expenses = db.Expenses.Include(e => e.Employee).Include(e => e.Project).Where(e => e.EmployeeID.Equals(employee.EmployeeID)).ToList();
                var reimbursementList = new List<Reimbursement>();
                foreach (var bar in expenses.OfType<Reimbursement>())
                {
                    reimbursementList.Add(bar);
                }
                return View(reimbursementList.ToList());
            }
            else return View("Login", "Account");
        }
        // GET: Expenses/CreditCardList
        public ActionResult CreditCardList()
        {
            var employee = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault();
            if (employee != null)
            {
                //ViewBag.AlertMessage = TempData["AlertMsg"] as string;
                var expenses = db.Expenses.Include(e => e.Employee).Include(e => e.Project).Where(e => e.EmployeeID.Equals(employee.EmployeeID)).ToList();
                var creditCardList = new List<CreditCardRequest>();
                foreach (var bar in expenses.OfType<CreditCardRequest>())
                {
                    creditCardList.Add(bar);
                }
                return View(creditCardList.ToList());
            }
            else return View("Login", "Account");
        }

        public ActionResult ExpensesTabs()
        {
            return View();
        }

        // GET: Expenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expenses/Create
        public ActionResult Create()
        {

            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return View();
        }
        //GET: Expenses/CreateCreditCardRequest
        public ActionResult CreateCreditCardRequest()
        {
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return View("SubmitCCRequest");
        }
        //POST: Expenses/CreateReimbursement
        [HttpPost]
        public ActionResult CreateCreditCardRequest([Bind(Include ="CreditCardRequestID,Currency,ActualAmount,Category,Rechargeable,Comment,ProjectNo")] CreditCardRequest ccreq)
        {
            ccreq.ApprovalStatus = Status.Pending;
            ccreq.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(ccreq);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }
            return View("SubmitCCRequest", ccreq);
        }
        // GET: Expenses/CreateReimbursement
        public ActionResult CreateReimbursement()
        {

            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return PartialView();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReimbursement([Bind(Include = "EmployeeID,ExpenseID,DateOfExpense,ActualAmount,Currency,Comment,Category,Rechargeable,ProjectNo")] Reimbursement expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }

            var allErrors = ModelState.Values.SelectMany(v => v.Errors);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View("CreateReimbursement", expense);
        }

        // POST: PerDiem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePerDiem([Bind(Include = "EmployeeID,FromDate,ToDate,Location,Currency,Rate,ActualAmount,Comment,ProjectNo,Rechargeable,")] PerDiem expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.Rate = 39;
            var numDays = (expense.ToDate - expense.FromDate).TotalDays;
            expense.ActualAmount = ((decimal)(39 * numDays));
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View("Create", "PerDiem", expense);
        }
        // POST: Mileage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMileage([Bind(Include = "EmployeeID,DateOfExpense,Currency,Rate,ActualAmount,Distance,FromLocation,ToLocation,Comment,ProjectNo,Rechargeable,")] Mileage expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.Rate = 0.4M;
            expense.ActualAmount = expense.Distance * expense.Rate;
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("ExpensesTabs");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View(expense);
        }
        [HttpPost]
        public ActionResult UpdateStatus(List<int> selectedExpenses, int status)
        {
            //int status is for the Status enum
            //0 is approved
            //1 is rejected
            //2 is pending
            if (selectedExpenses != null && selectedExpenses.Count >= 1)
            {
                var expenses = db.Expenses
                    .Where(t => selectedExpenses.Contains(t.ExpenseID))
                    .ToList();
                foreach (var e in expenses)
                {
                    e.ApprovalStatus = (Status)status;
                }
                db.SaveChanges();
                var result = new { success = true, status = status };
                return Json(result);
            }
            else return Json("fail");
        }
        [HttpPost]
        public ActionResult UpdateSingleStatus(int selectedExpenseID, int status)
        {
            //int status is for the Status enum
            //0 is approved
            //1 is rejected
            //2 is pending
            var expense = db.Expenses.Find(selectedExpenseID);
            expense.ApprovalStatus = (Status)status;
            db.SaveChanges();
            var result = new { success = true, status = status };
            return Json(result);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpenseID,ActualAmount,Currency,Category,Rechargeable,Comment,ApprovalStatus,EmployeeID,ProjectNo")] Expense expense)
        {
            if (ModelState.IsValid)
            {

ExpensesProjectMaster/Controllers/MileageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExpensesProjectMaster.Models.Entities;
using ExpensesProjectMaster.Models;

namespace ExpensesProjectMaster.Controllers
{
    [Authorize]
    public class MileageController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Mileage
        public ActionResult Index()
        {
            var employee = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault();
            var expenses = db.Expenses.Include(e => e.Employee).Include(e => e.Project).Where(e => e.EmployeeID.Equals(employee.EmployeeID)).ToList();
            var mileageList = new List<Mileage>();
            foreach (var bar in expenses.OfType<Mileage>())
            {
                mileageList.Add(bar);
            }
            return View(mileageList);
        }

        //// GET: Expenses/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Expense expense = db.Expenses.Find(id);
        //    if (expense == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(expense);
        //}

        // GET: Mileage/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName");
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return View("Create");
        }



        //// GET: Expenses/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Expense expense = db.Expenses.Find(id);
        //    if (expense == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
        //    ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
        //    return View(expense);
        //}

        //// POST: Expenses/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ExpenseID,ActualAmount,Currency,Category,Rechargeable,Comment,ApprovalStatus,EmployeeID,ProjectNo")] Expense expense)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(expense).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
        //    ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
        //    return View(expense);
        //}

        // GET: Expenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("ExpensesTabs", "Expenses");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpensesProjectMaster/Views/Expenses/Create.cshtml
@model ExpensesProjectMaster.Models.Entities.Expense

@{
    ViewBag.Title = "Create";
}

<div id="exTab2" class="container">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#1" data-toggle="tab">Reimbursement</a>
        </li>
        <li>
            <a href="#2" data-toggle="tab">Mileage</a>
        </li>
        <li>
            <a href="#3" data-toggle="tab">Per Diem</a>
        </li>
        <li>
            <a href="#4" data-toggle="tab">Credit Card Request</a>
        </li>
    </ul>

    <div class="tab-content clearfix">
        <div class="tab-pane active" id="1">
            @Html.Action("CreateReimbursement", "Expenses")
        </div>
        <div class="tab-pane" id="2">
            @Html.Action("Create", "Mileage")
        </div>
        <div class="tab-pane" id="3">
            @Html.Action("Create", "PerDiem")
        </div>
        <div class="tab-pane" id="4">
            @Html.Action("CreateCreditCardRequest", "Expenses")
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpensesProjectMaster/Views/Expenses/CreateReimbursement.cshtml
@model ExpensesProjectMaster.Models.Entities.Reimbursement

<script type="text/javascript">
    $(function () { // will trigger when the document is ready
        //Initialise any date pickers
        $('.datepicker').datepicker({ dateFormat: 'dd/mm/yy', minDate: '-3M', maxDate: 0 });
    });
</script>

@using (Html.BeginForm("CreateReimbursement", "Expenses"))
            {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectNo, "Project", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectNo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectNo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfExpense, "Expense Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DateOfExpense, new { @class = "form-control datepicker", placeholder = "Enter Expense Date here..." })
                @Html.ValidationMessageFor(model => model.DateOfExpense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Category, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Currency, "Select Currency", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActualAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActualAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActualAmount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="comment-field" class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rechargeable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Rechargeable)
                    @Html.ValidationMessageFor(model => model.Rechargeable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Expense Claim" class="btn btn-info" />
            </div>
        </div>
    </div>
}

ExpensesProjectMaster/Views/Expenses/CreditCardList.cshtml
@model IEnumerable<ExpensesProjectMaster.Models.Entities.CreditCardRequest>

@{ 
    Layout = null;
}
<br />
<p>
    <a href="@Url.Action("Create", "Expenses")" class="btn btn-success" role="button">Submit new claim</a>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActualAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Currency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rechargeable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActualAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Currency)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rechargeable)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovalStatus)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ExpenseID }, new {@class="btn btn-danger" })
        </td>
    </tr>
}

</table>

ExpensesProjectMaster/Views/Expenses/Delete.cshtml
@model ExpensesProjectMaster.Models.Entities.Expense

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rechargeable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rechargeable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>

    }
</div>

ExpensesProjectMaster/Views/Expenses/Details.cshtml
@model ExpensesProjectMaster.Models.Entities.Expense

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rechargeable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rechargeable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ExpenseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExpensesProjectMaster/Views/Expenses/ExpensesTabs.cshtml
@{
    
    ViewBag.Title = "Expenses";
}

<div id="exTab2" class="container">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#1" data-toggle="tab">Reimbursement</a>
        </li>
        <li>
            <a href="#2" data-toggle="tab">Mileage</a>
        </li>
        <li>
            <a href="#3" data-toggle="tab">Per Diem</a>
        </li>
        <li>
            <a href="#4" data-toggle="tab">Credit Card Requests</a>
        </li>
    </ul>

    <div class="tab-content clearfix">
        <div class="tab-pane active" id="1">
            @Html.Action("Index", "Expenses")
        </div>
        <div class="tab-pane" id="2">
            @Html.Action("Index", "Mileage")
        </div>
        <div class="tab-pane" id="3">
            @Html.Action("Index", "Perdiem")
        </div>
        <div class="tab-pane" id="4">
            @Html.Action("CreditCardList", "Expenses")
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}