ExpensesProjectMaster/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExpensesProjectMaster.Models.Entities;
using ExpensesProjectMaster.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ExpensesProjectMaster.Controllers
{
    [Authorize]
    public class ExpensesController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        // GET: Expenses
        public ActionResult Index()
        {
            var employee = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault();
            if (employee != null)
            {
                ViewBag.AlertMessage = TempData["AlertMsg"] as string;
                var expenses = db.Expenses.Include(e => e.Employee).Include(e => e.Project).Where(e => e.EmployeeID.Equals(employee.EmployeeID)).ToList();
                var reimbursementList = new List<Reimbursement>();
                foreach (var bar in expenses.OfType<Reimbursement>())
                {
                    reimbursementList.Add(bar);
                }
                return View(reimbursementList.ToList());
            }
            else return View("Login", "Account");
        }
        // GET: Expenses/CreditCardList
        public ActionResult CreditCardList()
        {
            var employee = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault();
            if (employee != null)
            {
                //ViewBag.AlertMessage = TempData["AlertMsg"] as string;
                var expenses = db.Expenses.Include(e => e.Employee).Include(e => e.Project).Where(e => e.EmployeeID.Equals(employee.EmployeeID)).ToList();
                var creditCardList = new List<CreditCardRequest>();
                foreach (var bar in expenses.OfType<CreditCardRequest>())
                {
                    creditCardList.Add(bar);
                }
                return View(creditCardList.ToList());
            }
            else return View("Login", "Account");
        }

        public ActionResult ExpensesTabs()
        {
            return View();
        }

        // GET: Expenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expenses/Create
        public ActionResult Create()
        {

            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return View();
        }
        //GET: Expenses/CreateCreditCardRequest
        public ActionResult CreateCreditCardRequest()
        {
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return View("SubmitCCRequest");
        }
        //POST: Expenses/CreateReimbursement
        [HttpPost]
        public ActionResult CreateCreditCardRequest([Bind(Include ="CreditCardRequestID,Currency,ActualAmount,Category,Rechargeable,Comment,ProjectNo")] CreditCardRequest ccreq)
        {
            ccreq.ApprovalStatus = Status.Pending;
            ccreq.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(ccreq);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }
            return View("SubmitCCRequest", ccreq);
        }
        // GET: Expenses/CreateReimbursement
        public ActionResult CreateReimbursement()
        {

            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name");
            return PartialView();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReimbursement([Bind(Include = "EmployeeID,ExpenseID,DateOfExpense,ActualAmount,Currency,Comment,Category,Rechargeable,ProjectNo")] Reimbursement expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }

            var allErrors = ModelState.Values.SelectMany(v => v.Errors);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View("CreateReimbursement", expense);
        }

        // POST: PerDiem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePerDiem([Bind(Include = "EmployeeID,FromDate,ToDate,Location,Currency,Rate,ActualAmount,Comment,ProjectNo,Rechargeable,")] PerDiem expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.Rate = 39;
            var numDays = (expense.ToDate - expense.FromDate).TotalDays;
            expense.ActualAmount = ((decimal)(39 * numDays));
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                TempData["AlertMsg"] = "Success";
                return RedirectToAction("ExpensesTabs");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View("Create", "PerDiem", expense);
        }
        // POST: Mileage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMileage([Bind(Include = "EmployeeID,DateOfExpense,Currency,Rate,ActualAmount,Distance,FromLocation,ToLocation,Comment,ProjectNo,Rechargeable,")] Mileage expense)
        {
            expense.ApprovalStatus = Status.Pending;
            expense.Rate = 0.4M;
            expense.ActualAmount = expense.Distance * expense.Rate;
            expense.EmployeeID = db.Employees.Where(e => e.Email.Equals(User.Identity.Name)).FirstOrDefault().EmployeeID;
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("ExpensesTabs");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FirstName", expense.EmployeeID);
            ViewBag.ProjectNo = new SelectList(db.Projects, "ProjectID", "Name", expense.ProjectNo);
            return View(expense);
        }
        [HttpPost]
        public ActionResult UpdateStatus(List<int> selectedExpenses, int status)
        {
            //int status is for the Status enum
            //0 is approved
            //1 is rejected
            //2 is pending
            if (selectedExpenses != null && selectedExpenses.Count >= 1)
            {
                var expenses = db.Expenses
                    .Where(t => selectedExpenses.Contains(t.ExpenseID))
                    .ToList();
                foreach (var e in expenses)
                {
                    e.ApprovalStatus = (Status)status;
                }
                db.SaveChanges();
                var result = new { success = true, status = status };
                return Json(result);
            }
            else return Json("fail");
        }
        [HttpPost]
        public ActionResult UpdateSingleStatus(int selectedExpenseID, int status)
        {
            //int status is for the Status enum
            //0 is approved
            //1 is rejected
            //2 is pending
            var expense = db.Expenses.Find(selectedExpenseID);
            expense.ApprovalStatus = (Status)status;
            db.SaveChanges();
            var result = new { success = true, status = status };
            return Json(result);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpenseID,ActualAmount,Currency,Category,Rechargeable,Comment,ApprovalStatus,EmployeeID,ProjectNo")] Expense expense)
        {
            if (ModelState.IsValid)
            {

ExpensesProjectMaster/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - V1 Expenses</title>
    
    @*@Styles.Render("~/Content/Lumino")*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Lumino")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/themes/base/core.css")"
          rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/datepicker.css")"
          rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/theme.css")"
          rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"
            type="text/javascript"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">V1 Expenses</a>
                <ul class="user-menu">
                    
                    <li class="dropdown pull-right">
                        <a href="@{if (ViewBag.WelcomeMessage.Equals("Log in"))
                            {
                            @Url.Action("Login", "Account")
                            }
                        else{
                            @*@Url.Action("Login", "Account")*@
                                }
                            } "><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg>@ViewBag.WelcomeMessage   |<span>    </span> </a>
                            @if (Request.IsAuthenticated)
                            {
                                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                {
                                    @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logoutForm').submit()">|   Log off</a>

                                }
                            }
                    </li>
                </ul>
            </div>

        </div><!-- /.container-fluid -->
    </nav>
    
   
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
    
            <!-- Employee View-->
            @if (User.IsInRole("Employee") || User.IsInRole("Finance") || User.IsInRole("Manager") || User.IsInRole("Receptionist"))
            {
            <li>@Html.ActionLink("My Expenses", "ExpensesTabs", "Expenses")</li>
            
            }

            @if (User.IsInRole("Finance"))
            {
            <!--Finance View-->
            <li>@Html.ActionLink("Approved Claims", "ApprovedClaims", "Finance")</li>
            }
            @if (User.IsInRole("Receptionist"))
            {
                <!--Receptionist View-->
                <li>@Html.ActionLink("Credit Card Requests", "ApprovedCreditCardRequests", "Receptionist")</li>
            }

            @if (User.IsInRole("Manager"))
            {
            <!--Manager View-->
            <li>@Html.ActionLink("Pending Claims", "PendingClaims", "Manager")</li>
            }
            <!--Everybody sees FAQs-->
            <li>@Html.ActionLink("FAQS", "FAQS", "Home")</li>




            <li role="presentation" class="divider"></li>
            @*<li><a href=@Url.Action("Login", "Accounts")><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Login Page</a></li>*@
        </ul>
    </div><!--/.sidebar-->

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="/"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
                <li class="active">@ViewBag.Title</li>
            </ol>
        </div><!--/.row-->

        <div class="row">
            <div class="col-lg-12">

                @RenderBody()


            </div>
        </div><!--/.row-->

        
    </div>	<!--/.main-->

    

    <script>
		$('#calendar').datepicker({
		});

		!function ($) {
		    $(document).on("click","ul.nav li.parent > a > span.icon", function(){
		        $(this).find('em:first').toggleClass("glyphicon-minus");
		    });
		    $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
		}(window.jQuery);

		$(window).on('resize', function () {
		  if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
		})
		$(window).on('resize', function () {
		  if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
		})
    </script>
</body>
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</html>